version: "3.8"

services:
  ### main application service ###
  app:
    init: true
    image: demo/app
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
    restart: always
    volumes:
      - ./log/gpsdemo:/code/log
      - /dev:/dev
    devices:
      - /dev/ttyS1:/dev/ttyS1
    networks:
      - smms-network
networks:
  smms-network:
    driver: bridge